# Generated by Django 4.2.4 on 2023-08-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='vive',
            field=models.BooleanField(default=True),
        ),
    ]
