# Generated by Django 4.2.4 on 2023-08-29 21:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0002_persona_created_persona_updated_persona_vive'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='legajo',
            field=ckeditor.fields.RichTextField(default='legajo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
